### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by icefoxen**
Disambiguate time zones.  I can never remember what BST is.

### CODE REVIEW

**Comment by Lokathor** [comment]
We're one hour east of pacific time @ZeGentzy

**Comment by ZeGentzy** [comment]
I know that, but that's not stopping me from feeling excluded :P

**Comment by icefoxen** [comment]
I tried to at least bracket the most common times. I feel like eastern Europe and India get a bit left out, alas, but...

**Comment by distransient** [comment]
I can't Review but consider this a positive review :shipit:

]

**Comment by Osspial** [comment]
Uh, is the EST conversion wrong? This meeting is happening at 3:00 PM (15:00), not 4:00 (16:00)

**Comment by Lokathor** [comment]
yes, there was a goof because of daylight savings.

I'll throw up another PR to fix this in just a moment.

**Comment by Lokathor** [comment]
https://github.com/rust-gamedev/wg/pull/37

**Pull request merged**
