### PR TITLE
Added meeting info

### PR DESCRIPTION
**Pull request by AlexEne**
Added google calendar meeting invite (will be updated with a link for the location).

### CODE REVIEW

**Comment by AlexEne** [comment]
Solves  #16

**Comment by AlexEne** [comment]
Sorry if It seems like I rush-merge this, but Wednesday is getting closer. We can change the location afterwards.

**Comment by msiglreith** [comment]
Might be me but the google calender link doesn't work. It shows an error that it couldn't find the appointment

**Comment by AlexEne** [comment]
Let me try and see what's happening.

**Comment by AlexEne** [comment]
Does it work now for you?

**Comment by msiglreith** [comment]
@AlexEne thanks, but still the same issue

**Comment by Lokathor** [comment]
I also get an error

**Comment by AlexEne** [comment]
It's ok google calenadar is a pain it seems that I need to create another (public calendar) and publish that there... Who designs these things is beyond me. What does publish even mean if I am the only one seeing it by default (and they show no warnings or hints) 😆

**Comment by AlexEne** [comment]
I've fixed it now

**Pull request merged**
